### ISSUE TITLE
TrocoIterator - hasNext com condição de for loop infinita

### ISSUE THREAD

**Issue by ccfei652** [ccfei652/Source-Code-Inspection#5]
A condição do for, sua inicialização e a incrementação da variável acaba resultando em um loop infinito:

`hasNext` - linhas 61 a 65 

```Java
for (int i = 6; i >= 0; i++) {
    if (troco.papeisMoeda[i] != null) {
        return true;
    }
}
```

Esperado:

Que a variável percorra todos os índices do array papeisMoeda, ou seja, percorra os índices de 1 a 5.

**Comment by VictorGni** [comment]
Issue corrigida no commit 954ff9d8a7cb28bea83418cf08d743e053d259a5
