### ISSUE TITLE
TrocoIterator - next com condição de for loop infinita

### ISSUE THREAD

**Issue by ccfei652** [ccfei652/Source-Code-Inspection#7]
A condição do for, sua inicialização e a incrementação da variável acaba resultando em um loop infinito:

`next` - linhas 72 a 77

```Java
 for (int i = 6; i >= 0 && ret != null; i++) {
    if (troco.papeisMoeda[i] != null) {
        ret = troco.papeisMoeda[i];
        troco.papeisMoeda[i] = null;
    }
}
```

Esperado:

Que a variável percorra todos os índices do array papeisMoeda, ou seja, percorra os índices de 1 a 5.

**Comment by VictorGni** [comment]
Corrigido a condição do For - Commit c35d681342ad1329a1759da0cf44fa0c8fb1c7fd
