### ISSUE TITLE
TrocoIterator - next com condição de loop for nunca válida (ret = null)

### ISSUE THREAD

**Issue by ccfei652** [ccfei652/Source-Code-Inspection#9]
A váriavel ret é definida como "null', porém o `for` na linha 72 define que ret deve ser diferente de "null", caindo em condição false sempre.

`next` - linha 72

```Java
PapelMoeda ret = null;
for (int i = 6; i >= 0 && ret != null; i++) {
    if (troco.papeisMoeda[i] != null) {
        ret = troco.papeisMoeda[i];
        troco.papeisMoeda[i] = null;
    }
}
```

Esperado: 

Loop ter condição válida para entrar, ou seja, remover a condição `&& ret != null` para que o loop seja acessado.

**Comment by VictorGni** [comment]
Realizado a correção no commit - https://github.com/ccfei652/Source-Code-Inspection/commit/0d28aeeee40895fbde25f82712d147614c755670
